name: Deployment
on:
  push:
    branches:
      - "*"
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy-gh-pages.yml
